# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

# File: start.yml
stages:
- stage: Angular
  jobs:
  - job: angularinstall
    steps:
      - script: npm install angular
      

